# OpenAI Chat Proxy 配置文件示例
# 复制此文件为 openai-chat-proxy-config.yaml 并根据需要修改

# 连接超时时间(秒)
timeout: 30

# 转发的目标基础URL
# 可以是官方API: https://api.openai.com
# 也可以是其他兼容的API服务: https://api.your-alt-service.com
base_url: "https://api.openai.com"

# 代理服务器URL(如果需要)
# 示例: http://127.0.0.1:7890
proxy: null

# 自定义转发目标路径
# 接收的请求路径始终为 /v1/chat/completions
# 但会将请求转发到此处指定的目标路径
# 例如，设置为 "/chat" 时，请求 /v1/chat/completions 会被转发到 https://api.openai.com/chat
proxy_url_path: "/v1/chat/completions"

# 字段别名映射
# 定义请求JSON数据中字段名的转换规则
# 将请求中的原始字段名映射为目标服务需要的字段名
field_aliases:
  # "原始字段名": "目标字段名"
  # 例如，将标准OpenAI请求中的model字段转换为model_id:
  # "model": "model_id"
  # 保持为空对象时不进行任何转换
  
# API密钥映射
# 前端密钥到实际密钥的映射关系
# 可以使用自定义前端密钥简化管理和控制访问权限
api_keys:
  # 前端密钥: 实际OpenAI API密钥
  "my_key_1": "sk-actual-openai-key-xxxxx"
  "my_test_key": "sk-another-openai-key-yyyyy"

# IP白名单(留空表示允许所有IP)
ip_whitelist: 
  # - "127.0.0.1"
  # - "192.168.1.100"

# IP黑名单
ip_blacklist:
  # - "10.0.0.1"

# 日志设置
# 是否记录请求数据
log_requests: false
# 是否记录响应数据
log_responses: false 